import Foundation

let currencyLongNames = [
    "AUD": "Australian Dollar",
    "BGN": "Bulgarian Lev",
    "BRL": "Brazilian Real",
    "CAD": "Canadian Dollar",
    "CHF": "Swiss Franc",
    "CNY": "Chinese Yuan",
    "CZK": "Czech Koruna",
    "DKK": "Danish Krone",
    "EUR": "Euro",
    "GBP": "British Pound",
    "HKD": "Hong Kong Dollar",
    "HRK": "Croatian Kuna",
    "HUF": "Hungarian Forint",
    "IDR": "Indonesian Rupiah",
    "ILS": "Israeli New Shekel",
    "INR": "Indian Rupee",
    "JPY": "Japanese Yen",
    "KRW": "South Korean Won",
    "MXN": "Mexican Peso",
    "MYR": "Malaysian Ringgit",
    "NOK": "Norwegian Krone",
    "NZD": "New Zealand Dollar",
    "PHP": "Philippine Peso",
    "PLN": "Polish Zloty",
    "RON": "Romanian Leu",
    "RUB": "Russian Ruble",
    "SEK": "Swedish Krona",
    "SGD": "Singapore Dollar",
    "THB": "Thai Baht",
    "TRY": "Turkish Lira",
    "USD": "US Dollar",
    "ZAR": "South African Rand",
]

let initialRates = """
{
    "base": "USD",
    "date": "2017-10-31",
    "rates": {
        "AUD": 1.521,
        "BGN": 1.9558,
        "BRL": 3.8059,
        "CAD": 1.5004,
        "CHF": 1.1622,
        "CNY": 7.7177,
        "CZK": 25.669,
        "DKK": 7.4412,
        "GBP": 0.87853,
        "HKD": 9.0769,
        "HRK": 7.5225,
        "HUF": 311.64,
        "IDR": 15787.0,
        "ILS": 4.0992,
        "INR": 75.356,
        "JPY": 132.0,
        "KRW": 1301.5,
        "MXN": 22.296,
        "MYR": 4.9252,
        "NOK": 9.5238,
        "NZD": 1.7005,
        "PHP": 60.045,
        "PLN": 4.244,
        "RON": 4.6005,
        "RUB": 67.874,
        "SEK": 9.7415,
        "SGD": 1.586,
        "THB": 38.65,
        "TRY": 4.4164,
        "USD": 1.0,
        "ZAR": 16.434
    }
}
"""
